### ISSUE TITLE
Upravit HodinZaSemestrXX u předmětu

### ISSUE THREAD

**Issue by NovotMartin** [NovotMartin/AnalyzaRozvrhu#4]
Upravit property:

- HodinZaSemestrCv
- HodinZaSemestrSe
- HodinZaSemestrPr

Ve tříde Predmet tak, aby v ní vždy byl přepočítaný rozsah na jednotku HOD/SEM (buď z excel dotazníku nebo z _JednotekPrednasek_ a _JednotkaPrednasek_)

Potom upravit komentář u těch properties ve třídě Predmet aby tam nebylo TODO něbo tak něco.

**Comment by OpltFrantisek** [comment]
Hotovo 💃
